services:
  db:
    container_name: crypto_tracker_db
    image: postgres:18-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - cryptodata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    container_name: crypto_redis
    image: redis/8.6-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  celery-worker:
    build: .
    command: >
      bash -c "
      echo 'Waiting for database to be ready...' &&
      until pg_isready -h db -p 5432 -U \"${POSTGRES_USER:-crypto_user}\" -d \"${POSTGRES_DB:-crypto_tracker}\"; do
        echo 'Database is unavailable - sleeping' &&
        sleep 2;
      done &&
      echo 'Database is up - running migrations...' &&
      alembic upgrade head &&
      echo 'Starting Celery worker...' &&
      exec celery -A src.celery_app worker -l info -Q prices -c 2
      "
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app

  celery-beat:
    build: .
    command: >
      bash -c "
      echo 'Waiting for database to be ready...' &&
      until pg_isready -h db -p 5432 -U \"${POSTGRES_USER:-crypto_user}\" -d \"${POSTGRES_DB:-crypto_tracker}\"; do
        echo 'Database is unavailable - sleeping' &&
        sleep 2;
      done &&
      echo 'Database is up - running migrations...' &&
      alembic upgrade head &&
      echo 'Starting Celery beat...' &&
      exec celery -A src.celery_app beat -l info
      "
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app

volumes:
  cryptodata:
