"""create_prices_table

Revision ID: 4d52febd9bfa
Revises: 
Create Date: 2026-04-24 12:25:34.181693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d52febd9bfa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prices',
    sa.Column('ticker', postgresql.ENUM('BTC_USD', 'ETH_USD', name='tickerenum'), nullable=False),
    sa.Column('time', postgresql.TIMESTAMP(timezone=True, precision=3), nullable=False),
    sa.Column('current_price', sa.NUMERIC(precision=20, scale=8), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'time', name='uq_prices_ticker_time')
    )
    op.create_index('ix_prices_ticker_time', 'prices', ['ticker', 'time'], unique=False, postgresql_ops={'time': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prices_ticker_time', table_name='prices', postgresql_ops={'time': 'DESC'})
    op.drop_table('prices')
    # ### end Alembic commands ###
